from sources.agsus import AgsusScraper
from sources.einstein import EinsteinScraper
from sources.fleury import FleuryScraper
from sources.gupy import (
    AacdScraper,
    AfipScraper,
    BaiaSulScraper,
    BpScraper,
    CajuruScraper,
    CaudaGupyScraper,
    DasaScraper,
    DavitaScraper,
    EvangelicoScraper,
    FhsaScraper,
    FidiScraper,
    HaocScraper,
    HapvidaScraper,
    HmbfmScraper,
    ImedScraper,
    InovaSaudeScraper,
    InstitutoMaisSaudeScraper,
    IrmaDulceScraper,
    IrsslScraper,
    MarcelinoChampagnatScraper,
    MedMaisScraper,
    MoinhosScraper,
    OncologiaDorScraper,
    PilarScraper,
    RastButantaScraper,
    RedeAmericasScraper,
    RedeDorScraper,
    SabinScraper,
    SantaCasaBaScraper,
    SantaCasaBhScraper,
    SantaCasaPoaScraper,
    SaoLucasRibeiraoScraper,
    SaoLucasScraper,
    SeconciSpScraper,
    SpdmScraper,
    UnimedScraper,
    VeraCruzScraper,
)
from sources.hcor import HcorScraper
from sources.hsl_sirio import HslSirioScraper
from sources.inca import IncaScraper
from sources.mater_dei import MaterDeiScraper
from sources.pci_concursos import PciConcursosScraper
from sources.solides import SolidesSaudeScraper

SCRAPERS = {
    RedeDorScraper.slug: RedeDorScraper,
    HapvidaScraper.slug: HapvidaScraper,
    IrsslScraper.slug: IrsslScraper,
    SantaCasaBhScraper.slug: SantaCasaBhScraper,
    SantaCasaPoaScraper.slug: SantaCasaPoaScraper,
    SantaCasaBaScraper.slug: SantaCasaBaScraper,
    AacdScraper.slug: AacdScraper,
    RedeAmericasScraper.slug: RedeAmericasScraper,
    MoinhosScraper.slug: MoinhosScraper,
    BpScraper.slug: BpScraper,
    EinsteinScraper.slug: EinsteinScraper,
    FleuryScraper.slug: FleuryScraper,
    HaocScraper.slug: HaocScraper,
    HcorScraper.slug: HcorScraper,
    MaterDeiScraper.slug: MaterDeiScraper,
    HslSirioScraper.slug: HslSirioScraper,
    PciConcursosScraper.slug: PciConcursosScraper,
    AgsusScraper.slug: AgsusScraper,
    IncaScraper.slug: IncaScraper,
    SpdmScraper.slug: SpdmScraper,
    DavitaScraper.slug: DavitaScraper,
    SeconciSpScraper.slug: SeconciSpScraper,
    DasaScraper.slug: DasaScraper,
    SabinScraper.slug: SabinScraper,
    FidiScraper.slug: FidiScraper,
    UnimedScraper.slug: UnimedScraper,
    SolidesSaudeScraper.slug: SolidesSaudeScraper,
    VeraCruzScraper.slug: VeraCruzScraper,
    BaiaSulScraper.slug: BaiaSulScraper,
    FhsaScraper.slug: FhsaScraper,
    PilarScraper.slug: PilarScraper,
    SaoLucasScraper.slug: SaoLucasScraper,
    MedMaisScraper.slug: MedMaisScraper,
    ImedScraper.slug: ImedScraper,
    OncologiaDorScraper.slug: OncologiaDorScraper,
    AfipScraper.slug: AfipScraper,
    MarcelinoChampagnatScraper.slug: MarcelinoChampagnatScraper,
    SaoLucasRibeiraoScraper.slug: SaoLucasRibeiraoScraper,
    CajuruScraper.slug: CajuruScraper,
    IrmaDulceScraper.slug: IrmaDulceScraper,
    InovaSaudeScraper.slug: InovaSaudeScraper,
    InstitutoMaisSaudeScraper.slug: InstitutoMaisSaudeScraper,
    RastButantaScraper.slug: RastButantaScraper,
    EvangelicoScraper.slug: EvangelicoScraper,
    HmbfmScraper.slug: HmbfmScraper,
    CaudaGupyScraper.slug: CaudaGupyScraper,
}
