export type JobSourceMeta = {
  id: string;
  name: string;
  shortName: string;
  url: string;
  sector: "Público" | "Privado" | "Filantrópico";
  logo: string;
};

/**
 * Fontes BR activas (scrapers-br/). Logos na home — grelha igual ao PT.
 */
export const JOB_SOURCES: JobSourceMeta[] = [
  {
    id: "pci_concursos",
    name: "PCI Concursos — Saúde",
    shortName: "PCI Concursos",
    url: "https://www.pciconcursos.com.br/vagas/saude/",
    sector: "Público",
    logo: "/partners/pci-concursos-v2.png",
  },
  {
    id: "agsus",
    name: "AgSUS — Agência Brasileira de Apoio à Gestão do SUS",
    shortName: "AgSUS",
    url: "https://agenciasus.org.br/trabalheconosco/",
    sector: "Público",
    logo: "/partners/agsus-v2.png",
  },
  {
    id: "inca",
    name: "INCA — Instituto Nacional de Câncer",
    shortName: "INCA",
    url: "https://www.gov.br/inca/pt-br/acesso-a-informacao/institucional/concurso-publico",
    sector: "Público",
    logo: "/partners/inca-v2.png",
  },
  {
    id: "rededor",
    name: "Rede D'Or São Luiz",
    shortName: "Rede D'Or",
    url: "https://rededor.gupy.io/",
    sector: "Privado",
    logo: "/partners/rededor.png",
  },
  {
    id: "hapvida",
    name: "Hapvida NotreDame Intermédica",
    shortName: "Hapvida",
    url: "https://hapvidandi.gupy.io/",
    sector: "Privado",
    logo: "/partners/hapvida.png",
  },
  {
    id: "irssl",
    name: "IRSSL — Instituto de Responsabilidade Social Sírio-Libanês",
    shortName: "IRSSL",
    url: "https://irssl.gupy.io/",
    sector: "Público",
    logo: "/partners/irssl.png",
  },
  {
    id: "hsl_sirio",
    name: "Hospital Sírio-Libanês",
    shortName: "Sírio-Libanês",
    url: "https://vagas.hsl.org.br/",
    sector: "Privado",
    logo: "/partners/hsl-sirio-v3.png",
  },
  {
    id: "santa_casa_bh",
    name: "Santa Casa de Misericórdia de Belo Horizonte",
    shortName: "Santa Casa BH",
    url: "https://santacasabh.gupy.io/",
    sector: "Filantrópico",
    logo: "/partners/santa-casa-bh.png",
  },
  {
    id: "santa_casa_poa",
    name: "Santa Casa de Misericórdia de Porto Alegre",
    shortName: "Santa Casa POA",
    url: "https://santacasa.gupy.io/",
    sector: "Filantrópico",
    logo: "/partners/santa-casa-poa-v2.png",
  },
  {
    id: "santa_casa_ba",
    name: "Santa Casa da Bahia",
    shortName: "Santa Casa BA",
    url: "https://santacasaba.gupy.io/",
    sector: "Filantrópico",
    logo: "/partners/santa-casa-ba-v2.png",
  },
  {
    id: "aacd",
    name: "AACD — Associação de Assistência à Criança Deficiente",
    shortName: "AACD",
    url: "https://aacd.gupy.io/",
    sector: "Filantrópico",
    logo: "/partners/aacd-v2.png",
  },
  {
    id: "redeamericas",
    name: "Rede Américas (Ímpar)",
    shortName: "Rede Américas",
    url: "https://redeamericas.gupy.io/",
    sector: "Privado",
    logo: "/partners/redeamericas.png",
  },
  {
    id: "moinhos",
    name: "Hospital Moinhos de Vento",
    shortName: "Moinhos",
    url: "https://hospitalmoinhos.gupy.io/",
    sector: "Privado",
    logo: "/partners/moinhos.png",
  },
  {
    id: "bp",
    name: "BP — Beneficência Portuguesa de São Paulo",
    shortName: "BP",
    url: "https://vemserbp.gupy.io/",
    sector: "Privado",
    logo: "/partners/bp.png",
  },
  {
    id: "einstein",
    name: "Hospital Israelita Albert Einstein",
    shortName: "Einstein",
    url: "https://trabalheconosco.vagas.com.br/alberteinstein/oportunidades",
    sector: "Privado",
    logo: "/partners/einstein.png",
  },
  {
    id: "haoc",
    name: "Hospital Alemão Oswaldo Cruz",
    shortName: "Oswaldo Cruz",
    url: "https://www.hospitaloswaldocruz.org.br/trabalhe-conosco/",
    sector: "Privado",
    logo: "/partners/haoc-v3.png",
  },
  {
    id: "hcor",
    name: "HCor — Hospital do Coração",
    shortName: "HCor",
    url: "https://hcoracao.pandape.infojobs.com.br/",
    sector: "Filantrópico",
    logo: "/partners/hcor-v3.png",
  },
  {
    id: "mater_dei",
    name: "Rede Mater Dei de Saúde",
    shortName: "Mater Dei",
    url: "https://app.jobconvo.com/pt-br/careers/hospital-mater-dei/6fcf22e3-009f-40e9-94ea-25e36ed95d22/",
    sector: "Privado",
    logo: "/partners/mater-dei-v2.png",
  },
  {
    id: "spdm",
    name: "SPDM/PAIS — Associação Paulista para o Desenvolvimento da Medicina",
    shortName: "SPDM/PAIS",
    url: "https://spdmpais.gupy.io/",
    sector: "Público",
    logo: "/partners/spdm-v2.png",
  },
  {
    id: "davita",
    name: "DaVita Serviços Assistenciais",
    shortName: "DaVita",
    url: "https://servicosassistenciais.gupy.io/",
    sector: "Privado",
    logo: "/partners/davita-v2.png",
  },
  {
    id: "seconci_sp",
    name: "Seconci-SP",
    shortName: "Seconci-SP",
    url: "https://seconci-sp.gupy.io/",
    sector: "Filantrópico",
    logo: "/partners/seconci-sp-v2.png",
  },
  {
    id: "fleury",
    name: "Grupo Fleury",
    shortName: "Fleury",
    url: "https://trabalheconosco.vagas.com.br/grupo-fleury/oportunidades",
    sector: "Privado",
    logo: "/partners/fleury-v2.png",
  },
  {
    id: "dasa",
    name: "Dasa",
    shortName: "Dasa",
    url: "https://dasaassistencial.gupy.io/",
    sector: "Privado",
    logo: "/partners/dasa-v2.png",
  },
  {
    id: "sabin",
    name: "Grupo Sabin",
    shortName: "Sabin",
    url: "https://gruposabin.gupy.io/",
    sector: "Privado",
    logo: "/partners/sabin-v2.png",
  },
  {
    id: "fidi",
    name: "FIDI — Fundação Instituto de Pesquisa e Estudo de Diagnóstico por Imagem",
    shortName: "FIDI",
    url: "https://fidi.gupy.io/",
    sector: "Privado",
    logo: "/partners/fidi-v2.png",
  },
  {
    id: "unimed",
    name: "Unimed (cooperativas — top boards Gupy)",
    shortName: "Unimed",
    url: "https://unimedcampinas.gupy.io/",
    sector: "Privado",
    logo: "/partners/unimed-v2.png",
  },
  {
    id: "solides",
    name: "Solides — Unimeds e clínicas/home care",
    shortName: "Solides",
    url: "https://unimedjp.vagas.solides.com.br/",
    sector: "Privado",
    logo: "/partners/solides-v2.png",
  },
  {
    id: "vera_cruz",
    name: "Hospital Vera Cruz",
    shortName: "Vera Cruz",
    url: "https://veracruzhospital.gupy.io/",
    sector: "Privado",
    logo: "/partners/vera-cruz-v2.png",
  },
  {
    id: "baia_sul",
    name: "Hospital Baía Sul",
    shortName: "Baía Sul",
    url: "https://baiasulhospital.gupy.io/",
    sector: "Privado",
    logo: "/partners/baia-sul-v2.png",
  },
  {
    id: "fhsa",
    name: "Hospital São Francisco de Assis (FHSA)",
    shortName: "FHSA",
    url: "https://fhsfa.gupy.io/",
    sector: "Filantrópico",
    logo: "/partners/fhsa-v2.png",
  },
  {
    id: "pilar",
    name: "Pilar Hospital",
    shortName: "Pilar",
    url: "https://pilarhospital.gupy.io/",
    sector: "Privado",
    logo: "/partners/pilar-v2.png",
  },
  {
    id: "sao_lucas",
    name: "Hospital São Lucas",
    shortName: "São Lucas",
    url: "https://hospitalsaolucas.gupy.io/",
    sector: "Privado",
    logo: "/partners/sao-lucas-v2.png",
  },
  {
    id: "medmais",
    name: "MedMais",
    shortName: "MedMais",
    url: "https://medmais.gupy.io/",
    sector: "Privado",
    logo: "/partners/medmais-v2.png",
  },
  {
    id: "imed",
    name: "IMED — Instituto de Medicina, Estudos e Desenvolvimento",
    shortName: "IMED",
    url: "https://vagasimed.gupy.io/",
    sector: "Público",
    logo: "/partners/imed-v2.png",
  },
  {
    id: "oncologia_dor",
    name: "Oncologia D'Or",
    shortName: "Oncologia D'Or",
    url: "https://oncologiador.gupy.io/",
    sector: "Privado",
    logo: "/partners/oncologia-dor-v2.png",
  },
];

export function getSourceMeta(id: string) {
  return JOB_SOURCES.find((source) => source.id === id) ?? null;
}

export const SOURCE_META = Object.fromEntries(
  JOB_SOURCES.map((source) => [
    source.id,
    { name: source.name, url: source.url, sector: source.sector },
  ]),
) as Record<string, { name: string; url: string; sector: string }>;
