export type JobSourceMeta = {
  id: string;
  name: string;
  shortName: string;
  url: string;
  sector: "Público" | "Privado" | "IPSS";
  logo: string;
};

export const JOB_SOURCES: JobSourceMeta[] = [
  {
    id: "bep",
    name: "BEP — Bolsa de Emprego Público",
    shortName: "BEP",
    url: "https://www.bep.gov.pt/pages/oferta/Oferta_Pesquisa_basica.aspx",
    sector: "Público",
    logo: "/partners/bep.jpg",
  },
  {
    id: "dre",
    name: "Diário da República",
    shortName: "DRE",
    url: "https://diariodarepublica.pt/dr/home",
    sector: "Público",
    logo: "/partners/dre.png",
  },
  {
    id: "iefp",
    name: "IEFP — Ofertas de emprego",
    shortName: "IEFP",
    url: "https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaEmprego",
    sector: "Privado",
    logo: "/partners/iefp.png",
  },
  {
    id: "ipo_porto",
    name: "IPO Porto",
    shortName: "IPO Porto",
    url: "https://ipoporto.pt/nos-ipo/emprego-e-carreira/",
    sector: "Público",
    logo: "/partners/ipo-porto.png",
  },
  {
    id: "scml",
    name: "Santa Casa da Misericórdia de Lisboa",
    shortName: "Santa Casa Lisboa",
    url: "https://recrutamento.scml.pt/",
    sector: "IPSS",
    logo: "/partners/scml.svg",
  },
  {
    id: "scm_esposende",
    name: "Santa Casa da Misericórdia de Esposende",
    shortName: "SCM Esposende",
    url: "https://www.scmesposende.pt/recrutamento",
    sector: "IPSS",
    logo: "/partners/scm-esposende.svg",
  },
  {
    id: "cuf",
    name: "CUF / José de Mello",
    shortName: "CUF",
    url: "https://carreiras.cuf.pt/",
    sector: "Privado",
    logo: "/partners/cuf.png",
  },
  {
    id: "luz_saude",
    name: "Luz Saúde",
    shortName: "Luz Saúde",
    url: "https://www.hospitaldaluz.pt/",
    sector: "Privado",
    logo: "/partners/luz-saude.svg",
  },
  {
    id: "trofa_saude",
    name: "Trofa Saúde",
    shortName: "Trofa Saúde",
    url: "https://recrutamento.grupovnc.com/trofasaude/",
    sector: "Privado",
    logo: "/partners/trofa-saude.svg",
  },
  {
    id: "lusiadas",
    name: "Lusíadas",
    shortName: "Lusíadas",
    url: "https://www.lusiadas.pt/",
    sector: "Privado",
    logo: "/partners/lusiadas.svg",
  },
  {
    id: "joaquim_chaves",
    name: "Joaquim Chaves Saúde",
    shortName: "Joaquim Chaves",
    url: "https://recrutamento.jcs.pt/Offers",
    sector: "Privado",
    logo: "/partners/joaquim-chaves.png",
  },
  {
    id: "champalimaud",
    name: "Fundação Champalimaud",
    shortName: "Champalimaud",
    url: "https://www.fchampalimaud.org/pt-pt/posicoes-em-aberto",
    sector: "Privado",
    logo: "/partners/champalimaud.svg",
  },
  {
    id: "germano_de_sousa",
    name: "Grupo Germano de Sousa",
    shortName: "Germano de Sousa",
    url: "https://www.germanodesousa.com/contactos/ofertas-de-emprego/",
    sector: "Privado",
    logo: "/partners/germano-de-sousa.svg",
  },
  {
    id: "hpa",
    name: "Grupo HPA Saúde",
    shortName: "HPA Saúde",
    url: "https://www.grupohpa.com/pt/empregos/",
    sector: "Privado",
    logo: "/partners/hpa.png",
  },
  {
    id: "holon",
    name: "Farmácias Holon",
    shortName: "Holon",
    url: "https://www.farmaciasholon.pt/candidaturas/",
    sector: "Privado",
    logo: "/partners/holon.png",
  },
  {
    id: "aefful",
    name: "AEFFUL — Farmácia comunitária",
    shortName: "AEFFUL",
    url: "https://www.aefful.pt/farmacia/",
    sector: "Privado",
    logo: "/partners/aefful.png",
  },
  {
    id: "pharmabsc",
    name: "PHARMABSC — Recrutamento farmácia",
    shortName: "PHARMABSC",
    url: "https://pharmabsc.pt/category/recrutamento/",
    sector: "Privado",
    logo: "/partners/pharmabsc.png",
  },
  {
    id: "net_empregos",
    name: "Net-Empregos — Saúde / Medicina / Enfermagem",
    shortName: "Net-Empregos",
    url: "https://www.net-empregos.com/emprego-saude-medicina-enfermagem.asp",
    sector: "Privado",
    logo: "/partners/net-empregos.svg",
  },
  {
    id: "sapo_emprego",
    name: "SAPO Emprego — Saúde",
    shortName: "SAPO Emprego",
    url: "https://emprego.sapo.pt/offers?categoria=saude",
    sector: "Privado",
    logo: "/partners/sapo-emprego.svg",
  },
  {
    id: "scmp",
    name: "Misericórdia do Porto",
    shortName: "SCMP",
    url: "https://scmp.pt/oportunidades-de-recrutamento",
    sector: "IPSS",
    logo: "/partners/scmp.svg",
  },
  {
    id: "scm_faro",
    name: "Misericórdia de Faro",
    shortName: "SCM Faro",
    url: "https://misericordiafaro.pt/category/ofertas-de-emprego/",
    sector: "IPSS",
    logo: "/partners/scm-faro.svg",
  },
  {
    id: "ipst",
    name: "IPST — Procedimentos concursais",
    shortName: "IPST",
    url: "https://www.ipst.pt/index.php/pt/procedimentos-concursais",
    sector: "Público",
    logo: "/partners/ipst.svg",
  },
  {
    id: "inem",
    name: "INEM — Recrutamento",
    shortName: "INEM",
    url: "https://www.inem.pt/category/institucional/recrutamento/",
    sector: "Público",
    logo: "/partners/inem.svg",
  },
  {
    id: "uls_sao_jose",
    name: "ULS São José",
    shortName: "ULS São José",
    url: "https://www.ulssjose.min-saude.pt/concursos-de-admissao-de-pessoal/",
    sector: "Público",
    logo: "/partners/uls-sao-jose.svg",
  },
  {
    id: "uls_coimbra",
    name: "ULS Coimbra",
    shortName: "ULS Coimbra",
    url: "https://www.ulscoimbra.min-saude.pt/concursos/",
    sector: "Público",
    logo: "/partners/uls-coimbra.svg",
  },
  {
    id: "uls_sao_joao",
    name: "ULS São João",
    shortName: "ULS São João",
    url: "https://concursosrh-ulssjoao.min-saude.pt/processos-ativos",
    sector: "Público",
    logo: "/partners/uls-sao-joao.svg",
  },
];

export const SOURCE_META = Object.fromEntries(
  JOB_SOURCES.map((source) => [
    source.id,
    { name: source.name, url: source.url, sector: source.sector },
  ]),
) as Record<string, { name: string; url: string; sector: string }>;
